project_id = "tvmjjmwznomctlynhwnq"

[functions.get-tournaments]
verify_jwt = false

[functions.get-player-stats]
verify_jwt = false

[functions.get-sf6-tournaments]
verify_jwt = false

[functions.get-tekken8-tournaments]
verify_jwt = false